const DATA={high:'data/high_bus.geojson',ferry:'data/ferry.geojson',intermediate:'data/intermediate_bus.geojson',rail:'data/rail.geojson',stops:'data/stops.geojson',major:'data/major-stations.geojson'};
// Remove game-state copies saved by the previous release.
try { for(const key of ['jetlagLegal','jetlagLegalV2','jetlagStatusV2','jetlagUnsupportedV2','jetlagTaibeled'])localStorage.removeItem(key); } catch {}
const COLORS={high:'#d43f3a',ferry:'#0785c1',intermediate:'#e08a00',rail:'#6b4fa1'};
let legal=null; const originalData={};
function updateTransit(){for(const [k,data] of Object.entries(originalData))map.getSource(k)?.setData(document.querySelector("#insideOnly").checked&&legal?clipTransit(data,legal):data);}
const STOP_CATEGORIES={high:'high_bus',ferry:'ferry',intermediate:'intermediate_bus',rail:'rail'};
function updateStopFilters(){
  const categories=Object.entries(STOP_CATEGORIES).filter(([id])=>document.querySelector(`[data-layer="${id}"]`).checked).map(([,category])=>category);
  const filter=categories.length?['any',...categories.map(category=>['in',category,['get','categories']])]:['==',['literal',1],0];
  for(const id of ['stops','major'])if(map.getLayer(id))map.setFilter(id,filter);
  activePopup?.remove();
}
function save(key,value){try{sessionStorage.setItem(key,value)}catch{toast("Browser storage unavailable; keep this tab open")}}
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[153.03,-27.47],zoom:10.3,attributionControl:false});
map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');
let activePopup;
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function popup(){activePopup?.remove();activePopup=new maplibregl.Popup();return activePopup;}
const toast=(s)=>{let t=document.querySelector('#toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',3500)};
function setLegal(g){legal=g;document.querySelector('#areaNotice').hidden=!g;const src=map.getSource('legal');if(src)src.setData(g);save('jetlagLegalV2',JSON.stringify(g));updateTransit();document.querySelector('#fitBtn').disabled=!g;if(g)fitLegal();}
function fitLegal(){if(!legal)return;const b=turf.bbox(legal);if(!b.every(Number.isFinite))return;map.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:{top:90,bottom:50,left:30,right:30},maxZoom:14,duration:500})}
map.on('load',async()=>{try{for(const [k,url] of Object.entries(DATA)){const data=await fetch(url).then(r=>{if(!r.ok)throw Error('Could not load '+url);return r.json()});originalData[k]=data;map.addSource(k,{type:'geojson',data});if(['high','ferry','intermediate','rail'].includes(k)){map.addLayer({id:k,type:'line',source:k,layout:{visibility:(k==='high'||k==='ferry')?'visible':'none','line-cap':'round','line-join':'round'},paint:{'line-color':COLORS[k],'line-width':['interpolate',['linear'],['zoom'],9,2,13,5],'line-opacity':.82}});map.on('click',k,e=>{let p=e.features[0].properties;popup().setLngLat(e.lngLat).setHTML(`<b>Route ${escapeHTML(p.route)}</b><br>${escapeHTML(p.name)}<br><small>${k==='high'?'~15-minute-or-better Sunday daytime':k==='ferry'?'High-frequency Sunday ferry':k==='rail'?'~30-minute Sunday train network':'15–30 minute Sunday daytime'}</small>`).addTo(map)});map.on('mouseenter',k,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',k,()=>map.getCanvas().style.cursor='');}else{const major=k==='major';map.addLayer({id:k,type:'circle',source:k,layout:{visibility:major?'visible':'none'},paint:{'circle-radius':major?['interpolate',['linear'],['zoom'],9,3,14,7]:['interpolate',['linear'],['zoom'],10,1.5,14,4],'circle-color':major?'#152f4f':'#333','circle-stroke-color':'#fff','circle-stroke-width':major?1.5:.6,'circle-opacity':.85}});map.on('click',k,e=>{let p=e.features[0].properties,rs=Array.isArray(p.routes)?p.routes:JSON.parse(p.routes||'[]');popup().setLngLat(e.lngLat).setHTML(`<b>${escapeHTML(p.name)}</b><br>${escapeHTML(rs.join(', '))}`).addTo(map)})}}
updateStopFilters();
map.addSource('legal',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'legal-fill',type:'fill',source:'legal',paint:{'fill-color':'#20a66a','fill-opacity':.18}});map.addLayer({id:'legal-line',type:'line',source:'legal',paint:{'line-color':'#08784a','line-width':3,'line-opacity':.9}});const saved=sessionStorage.getItem('jetlagLegalV2');if(saved)try{setLegal(JSON.parse(saved));document.querySelector('#status').textContent=sessionStorage.getItem('jetlagStatusV2')||'Restored approximate possible area';document.querySelector('#insideOnly').disabled=sessionStorage.getItem('jetlagUnsupportedV2')==='true'}catch{};
}catch(err){document.querySelector('#status').textContent='Could not finish loading: '+err.message;console.error(err);}
});
document.querySelector('#menuBtn').onclick=()=>document.querySelector('#panel').classList.toggle('open');document.querySelector('#loadBtn').onclick=()=>document.querySelector('#fileInput').click();
document.querySelector('#fileInput').onchange=async e=>{try{if(!e.target.files.length)return;if(e.target.files[0].size>2*1024*1024)throw Error('Export exceeds the 2 MB limit');let j=JSON.parse(await e.target.files[0].text());let r=parseTaibeled(j);document.querySelector('#insideOnly').checked=false;setLegal(r.geom);let msg=`Applied ${r.count} question${r.count===1?'':'s'}`;if(r.notes.length)msg+=' · '+r.notes.join(' · ');if(r.unsupported?.length)msg+=` · not yet applied: ${[...new Set(r.unsupported)].join(', ')}`;document.querySelector('#status').textContent=msg;save('jetlagStatusV2',msg);save('jetlagUnsupportedV2',String(!!r.unsupported.length));document.querySelector('#insideOnly').disabled=!!r.unsupported.length;document.querySelector('#panel').classList.add('open');if(r.unsupported?.length)toast('Some Taibeled question types are shown in status but not yet applied to the overlay.')}catch(err){document.querySelector('#status').textContent='Could not read that Taibeled export';toast(err.message)}};
document.querySelectorAll('[data-layer]').forEach(x=>x.onchange=()=>{let id=x.dataset.layer;if(map.getLayer(id))map.setLayoutProperty(id,'visibility',x.checked?'visible':'none');updateStopFilters()});document.querySelector('#legalToggle').onchange=e=>['legal-fill','legal-line'].forEach(id=>map.getLayer(id)&&map.setLayoutProperty(id,'visibility',e.target.checked?'visible':'none'));document.querySelector('#fitBtn').onclick=fitLegal;document.querySelector('#clearBtn').onclick=()=>{legal=null;document.querySelector('#areaNotice').hidden=true;sessionStorage.removeItem('jetlagLegalV2');sessionStorage.removeItem('jetlagStatusV2');sessionStorage.removeItem('jetlagUnsupportedV2');document.querySelector('#insideOnly').checked=false;document.querySelector('#insideOnly').disabled=false;document.querySelector('#fitBtn').disabled=true;updateTransit();sessionStorage.removeItem('jetlagTaibeled');if(map.getSource('legal'))map.getSource('legal').setData({type:'FeatureCollection',features:[]});document.querySelector('#status').textContent='No game state loaded'};document.querySelector('#insideOnly').onchange=()=>{if(!legal){document.querySelector('#insideOnly').checked=false;toast('Load a game export first');return;}updateTransit();};
map.on('error',e=>{console.warn(e.error);document.querySelector('#mapStatus').textContent='Map loading problem — check your connection and reload';});
map.on('idle',()=>document.querySelector('#mapStatus').textContent='');
